const fs = require("fs");
const path = require("path");

function createCertificate({
  documentName,
  hash,
  owner,
  txHash,
  timestamp,
  network,
  format = "txt"
}) {
  const safeName = documentName.replace(/[^a-zA-Z0-9_-]+/g, "_");
  const baseName = `proof_certificate_${safeName}_${timestamp}`;

  if (format === "pdf") {
    const PDFDocument = require("pdfkit");
    const outPath = path.join(process.cwd(), `${baseName}.pdf`);
    const doc = new PDFDocument();
    doc.pipe(fs.createWriteStream(outPath));

    doc.fontSize(18).text("DocProof Certificate", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Document: ${documentName}`);
    doc.text(`Hash: ${hash}`);
    doc.text(`Owner: ${owner}`);
    doc.text(`Transaction: ${txHash}`);
    doc.text(`Timestamp: ${timestamp}`);
    doc.text(`Network: ${network}`);

    doc.end();
    return outPath;
  }

  const lines = [
    "DocProof Certificate",
    "",
    `Document: ${documentName}`,
    `Hash: ${hash}`,
    `Owner: ${owner}`,
    `Transaction: ${txHash}`,
    `Timestamp: ${timestamp}`,
    `Network: ${network}`
  ];

  const outPath = path.join(process.cwd(), `${baseName}.txt`);

  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  return outPath;
}

function parseCertificate(filePath) {
  // Supports parsing certificate.txt files in the format generated by createCertificate
  const content = fs.readFileSync(filePath, "utf8");
  const lines = content.split(/\r?\n/);

  const result = {};
  for (const line of lines) {
    const [key, ...rest] = line.split(":");
    if (!key || rest.length === 0) continue;
    const value = rest.join(":").trim();
    if (key === "Document") result.document = value;
    if (key === "Hash") result.hash = value;
    if (key === "Owner") result.owner = value;
    if (key === "Transaction") result.transaction = value;
    if (key === "Timestamp") result.timestamp = value;
    if (key === "Network") result.network = value;
  }

  return result;
}

module.exports = {
  createCertificate,
  parseCertificate
};
